#!/usr/bin/env python3

import sys
import math
from src.midpoint import *
from src.trapezoidal import *
from src.printage import *
from src.simpson import *

def verif(number):
    for i in range(len(number)):
        if number[i] < '0' or number[i] > '9':
            exit(84)
    return int(number)

def main(number):
    res = 0
    res = Midpoint(number)
    print("Midpoint:")
    print_result(res, number)
    print()
    res = trapezoidal(number)
    print("Trapezoidal:")
    print_result(res, number)
    print()
    res = simpson(number)
    print("Simpson:")
    print_result(res, number)

if __name__=='__main__':
    argument = sys.argv
    if (len(argument) != 2):
        exit(84)
    number = verif(argument[1])
    main(number)
